import { afterAll, describe, expect, test } from "bun:test";
import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

import { planAntigravityProject } from "../adapters/antigravity.js";
import { planClaudeProject } from "../adapters/claude.js";
import { planCodexProject } from "../adapters/codex.js";
import {
  composeContextEnvelope,
  composeContextEnvelopeHeader,
} from "../adapters/context-envelope.js";
import {
  GENERATED_SOURCE_CONSENT_GUIDANCE,
  GENERATED_SOURCE_NOTICE,
  GENERATED_SOURCE_WORKSPACE_GUIDANCE,
  generatedMarkdownNotice,
} from "../adapters/generated-notice.js";
import { planGrokProject } from "../adapters/grok.js";
import {
  OPENCODE_CONFIG_OCCUPIED_REMEDY_KEY,
  OPENCODE_CONFIG_PATH,
  planOpenCodeProject,
} from "../adapters/opencode.js";
import { planPiProject } from "../adapters/pi.js";
import {
  planSharedSkillPackageDirectory,
  SHARED_SKILL_OPENAI_YAML,
  SHARED_SKILLS_DISCOVERY_ROOT,
} from "../adapters/shared-skill.js";
import type {
  ProposedDirectoryMember,
  ProposedProjectDirectoryOutput,
} from "../adapters/project-plan.js";
import type { Skill } from "../schemas/skill.js";
import { parseGeneratedJsonc } from "./support/generated-notice.js";

const temporaryDirectories: string[] = [];

afterAll(() => {
  for (const directory of temporaryDirectories) {
    rmSync(directory, { recursive: true, force: true });
  }
});

function temporaryDirectory(prefix: string): string {
  const directory = mkdtempSync(join(tmpdir(), prefix));
  temporaryDirectories.push(directory);
  return directory;
}

function writeSkillPackage(
  root: string,
  files: Readonly<Record<string, { readonly bytes: string; readonly mode?: number }>>,
): void {
  for (const [relativePath, entry] of Object.entries(files)) {
    const path = join(root, relativePath);
    mkdirSync(join(path, ".."), { recursive: true });
    writeFileSync(path, entry.bytes, { mode: entry.mode ?? 0o644 });
    if (entry.mode !== undefined) chmodSync(path, entry.mode);
  }
}

function skillAt(path: string, modelInvocation: Skill["modelInvocation"]): Skill {
  return { dependencies: [], id: "review-pr", modelInvocation, path };
}

function memberAt(
  output: ProposedProjectDirectoryOutput,
  path: string,
): ProposedDirectoryMember {
  const member = output.members.find((candidate) => candidate.path === path);
  if (member === undefined) throw new Error(`expected ${path}`);
  return member;
}

function memberText(output: ProposedProjectDirectoryOutput, path: string): string {
  const member = memberAt(output, path);
  if (member.type !== "file") throw new Error(`expected file ${path}`);
  return Buffer.from(member.bytes).toString("utf8");
}

const ALLOWED_SOURCE_SKILL =
  "---\nname: review-pr\ndescription: Review a pull request.\n---\n\n# Review\n\nPreserved body bytes.\n";
const DISABLED_SOURCE_SKILL =
  "---\nname: review-pr\ndescription: Review a pull request.\nmetadata:\n  agent-profile-kit.model-invocation: disabled\n---\n\n# Review\n\nPreserved body bytes.\n";

/** One canonical Skill package with the notice targets plus supporting bytes. */
function writeNoticeSkillPackage(
  root: string,
  sourceSkill: string,
  extraFiles: Readonly<Record<string, { readonly bytes: string; readonly mode?: number }>> = {},
): void {
  writeSkillPackage(root, {
    "SKILL.md": { bytes: sourceSkill },
    "agents/openai.yaml": {
      bytes: "interface:\n  display_name: Review PR\n",
      mode: 0o600,
    },
    "scripts/run.sh": { bytes: "#!/bin/sh\necho review\n", mode: 0o755 },
    "agent-profile-kit.yaml": { bytes: "dependencies: []\n" },
    ...extraFiles,
  });
}

describe("generated-source notice policy", () => {
  test("states the generator, the Workspace source, and explicit changed-file consent", () => {
    expect(GENERATED_SOURCE_NOTICE).toBe("Generated by apkit.");
    expect(GENERATED_SOURCE_WORKSPACE_GUIDANCE).toBe(
      "Make lasting edits in the Workspace (apkit open).",
    );
    expect(GENERATED_SOURCE_CONSENT_GUIDANCE).toBe(
      "Replacing or removing independently changed files requires explicit consent in install, update, and uninstall.",
    );
    expect(GENERATED_SOURCE_CONSENT_GUIDANCE).not.toMatch(
      /automatically|overwritten|replaced on/i,
    );
    // Temporary Profile Installations are torn down by their own explicit
    // command, so the sentence names the commands whose consent gate it states.
    expect(GENERATED_SOURCE_CONSENT_GUIDANCE).toContain(
      "in install, update, and uninstall",
    );
  });
});

describe("installed Skill entry documents", () => {
  test("carry the notice as the first body line after frontmatter and keep the body", async () => {
    const source = temporaryDirectory("apk-notice-skill-allowed-");
    writeNoticeSkillPackage(source, ALLOWED_SOURCE_SKILL);

    const output = await planSharedSkillPackageDirectory(
      skillAt(source, "allowed"),
      ["qualified shared Skill package"],
      "codex",
    );

    const generated = memberText(output, "SKILL.md");
    expect(generated).toBe(
      "---\nname: review-pr\ndescription: Review a pull request.\n---\n" +
        `<!-- ${GENERATED_SOURCE_NOTICE} ${GENERATED_SOURCE_WORKSPACE_GUIDANCE} ${GENERATED_SOURCE_CONSENT_GUIDANCE} -->\n` +
        "\n# Review\n\nPreserved body bytes.\n",
    );
    expect(parseYaml(generated.slice(4, generated.indexOf("---\n", 4)))).toEqual({
      name: "review-pr",
      description: "Review a pull request.",
    });
  });

  test("keep the canonical frontmatter comments and policy comment placement when disabled", async () => {
    const source = temporaryDirectory("apk-notice-skill-disabled-");
    writeNoticeSkillPackage(source, DISABLED_SOURCE_SKILL);

    const output = await planSharedSkillPackageDirectory(
      skillAt(source, "disabled"),
      ["qualified shared Skill package"],
      "codex",
    );

    const generated = memberText(output, "SKILL.md");
    expect(generated.startsWith("---\nname: review-pr\n")).toBe(true);
    expect(generated).toContain(
      "# Agent Profile Kit: keep Skill invocation explicit.\ndisable-model-invocation: true\n",
    );
    expect(generated).toContain(
      `---\n<!-- ${GENERATED_SOURCE_NOTICE} ${GENERATED_SOURCE_WORKSPACE_GUIDANCE} ${GENERATED_SOURCE_CONSENT_GUIDANCE} -->\n`,
    );
    expect(generated).toEndWith("\n# Review\n\nPreserved body bytes.\n");
  });

  test("preserve supporting resource bytes and modes and the copied Codex policy file", async () => {
    const source = temporaryDirectory("apk-notice-skill-resources-");
    writeNoticeSkillPackage(source, ALLOWED_SOURCE_SKILL);

    const output = await planSharedSkillPackageDirectory(
      skillAt(source, "allowed"),
      ["qualified shared Skill package"],
      "codex",
    );

    expect(memberText(output, "scripts/run.sh")).toBe("#!/bin/sh\necho review\n");
    expect(memberAt(output, "scripts/run.sh").mode).toBe(0o755);
    expect(memberText(output, SHARED_SKILL_OPENAI_YAML)).toBe(
      "interface:\n  display_name: Review PR\n",
    );
    expect(memberAt(output, SHARED_SKILL_OPENAI_YAML).mode).toBe(0o600);
    expect(output.members.some((member) => member.path === "agent-profile-kit.yaml")).toBe(false);
    expect(readFileSync(join(source, "SKILL.md"), "utf8")).toBe(ALLOWED_SOURCE_SKILL);
  });

  test("add no new package requirement or ownership claim", async () => {
    const source = temporaryDirectory("apk-notice-skill-requirements-");
    writeNoticeSkillPackage(source, ALLOWED_SOURCE_SKILL);

    const allowed = await planSharedSkillPackageDirectory(
      skillAt(source, "allowed"),
      ["qualified shared Skill package"],
      "codex",
    );
    expect(allowed.requirements).toEqual(["qualified shared Skill package"]);

    const disabled = await planSharedSkillPackageDirectory(
      skillAt(source, "disabled"),
      ["qualified shared Skill package"],
      "codex",
    );
    expect(disabled.requirements).toEqual([
      "qualified shared Skill package",
      "Host prevents implicit model invocation while retaining explicit user invocation",
      "Shared .agents Skill policy prevents implicit invocation in SKILL.md and Codex agents/openai.yaml",
    ]);
  });

  test("keep exact shared-output coalescing across every qualified consumer", async () => {
    const source = temporaryDirectory("apk-notice-skill-coalesce-");
    writeNoticeSkillPackage(source, DISABLED_SOURCE_SKILL);
    const skill = skillAt(source, "disabled");

    const [codex, pi, antigravity, opencode] = await Promise.all([
      planCodexProject("engineering", [], [skill]),
      planPiProject("engineering", [], [skill]),
      planAntigravityProject("engineering", [], [skill]),
      planOpenCodeProject("engineering", [], [skill]),
    ]);

    const outputs = [codex, pi, antigravity, opencode].map((plan) => {
      const output = plan.outputs.find(
        (candidate): candidate is ProposedProjectDirectoryOutput =>
          candidate.type === "directory" &&
          candidate.path === `${SHARED_SKILLS_DISCOVERY_ROOT}/review-pr`,
      );
      if (output === undefined) throw new Error("expected shared Skill package output");
      return output;
    });
    const entryDocuments = outputs.map((output) => memberText(output, "SKILL.md"));
    expect(new Set(entryDocuments).size).toBe(1);
    expect(entryDocuments[0]).toContain(GENERATED_SOURCE_NOTICE);
    const policyFiles = outputs.map((output) => memberText(output, SHARED_SKILL_OPENAI_YAML));
    expect(new Set(policyFiles).size).toBe(1);
    expect(policyFiles[0]).toContain("allow_implicit_invocation: false");
    expect(policyFiles[0]).toContain(
      "# Agent Profile Kit: prevent implicit Skill invocation.\n  allow_implicit_invocation: false",
    );
  });

  test("reach the Claude and Grok Host-native Skill projections", async () => {
    const source = temporaryDirectory("apk-notice-skill-host-native-");
    writeNoticeSkillPackage(source, ALLOWED_SOURCE_SKILL);
    const skill = skillAt(source, "allowed");

    const [claude, grok] = await Promise.all([
      planClaudeProject("engineering", [], [skill]),
      planGrokProject("engineering", [], [skill]),
    ]);

    const noticeLine = `<!-- ${GENERATED_SOURCE_NOTICE} ${GENERATED_SOURCE_WORKSPACE_GUIDANCE} ${GENERATED_SOURCE_CONSENT_GUIDANCE} -->`;
    const claudeOutput = claude.outputs.find(
      (output): output is ProposedProjectDirectoryOutput =>
        output.type === "directory" && output.path === ".claude/skills/review-pr",
    );
    const grokOutput = grok.outputs.find(
      (output): output is ProposedProjectDirectoryOutput =>
        output.type === "directory" && output.path === ".grok/skills/review-pr",
    );
    if (claudeOutput === undefined || grokOutput === undefined) {
      throw new Error("expected Host-native Skill package outputs");
    }
    expect(memberText(claudeOutput, "SKILL.md")).toContain(`---\n${noticeLine}\n`);
    expect(memberText(grokOutput, "SKILL.md")).toContain(`---\n${noticeLine}\n`);
  });
});

describe("composed Context output", () => {
  test("names its generated source with valid Markdown guidance", () => {
    const header = composeContextEnvelopeHeader("engineering");
    expect(header.split("\n")[0]).toBe("# Agent Profile Kit Context — Profile: engineering");
    expect(header).toContain(
      `<!-- ${GENERATED_SOURCE_NOTICE} ${GENERATED_SOURCE_WORKSPACE_GUIDANCE} ${GENERATED_SOURCE_CONSENT_GUIDANCE} -->`,
    );
    expect(header).toContain(
      "Repository-owned project instructions, including AGENTS.md, take precedence when they conflict with this material.",
    );
  });

  test("carries the notice once in a composed envelope without module boundary markers", () => {
    const composed = composeContextEnvelope("engineering", [
      { content: "Follow project conventions.\n", id: "team-rules" },
    ]);
    const occurrences = composed.split(GENERATED_SOURCE_NOTICE).length - 1;
    expect(occurrences).toBe(1);
    expect(composed).not.toMatch(/<!-- (End )?Context Module:/);
    expect(composed).toContain("Follow project conventions.\n");
  });
});

describe("per-module Antigravity Context rules", () => {
  test("carry the notice once in the envelope rule and in every module rule", async () => {
    const plan = await planAntigravityProject(
      "engineering",
      [{ content: "Prefer concise communication.\n", id: "communication" }],
      [],
    );
    const notice = generatedMarkdownNotice();
    const [envelope, moduleRule] = plan.outputs;
    if (envelope?.type !== "file" || moduleRule?.type !== "file") {
      throw new Error("expected always-on rule outputs");
    }
    expect(String(envelope.bytes).split(notice).length - 1).toBe(1);
    expect(String(moduleRule.bytes)).toBe(
      "---\ntrigger: always_on\n---\n\n" +
        `${notice}\n` +
        "<!-- Context Module: communication -->\nPrefer concise communication.\n<!-- End Context Module: communication -->\n",
    );
  });
});

describe("comment-capable generated Host configuration", () => {
  test("carries a JSONC notice and project-scope alternative configuration guidance", async () => {
    const plan = await planOpenCodeProject("engineering", [
      { content: "Follow project conventions.\n", id: "team-rules" },
    ], []);

    const config = plan.outputs.find(
      (output) => output.type === "file" && output.path === OPENCODE_CONFIG_PATH,
    );
    if (config === undefined || config.type !== "file") {
      throw new Error("expected OpenCode configuration output");
    }
    const source = String(config.bytes);

    const commentLines = source.split("\n").filter((line) => line.startsWith("//"));
    expect(commentLines.length).toBeGreaterThan(0);
    expect(commentLines.every((line) => line.length <= 92)).toBe(true);
    const guidance = commentLines.map((line) => line.replace(/^\/\/ /, "")).join(" ");
    expect(guidance).toContain(GENERATED_SOURCE_NOTICE);
    expect(guidance).toContain(GENERATED_SOURCE_CONSENT_GUIDANCE);
    expect(guidance).toContain("project configuration files this generator does not claim");
    expect(guidance).toContain("opencode.json or .opencode/opencode.json");
    expect(guidance).toContain(
      "Project-specific settings stay in the Project, not in personal or global OpenCode configuration.",
    );
    expect(guidance).not.toContain("Make lasting edits in the Workspace");

    // The notice is a leading comment block: no comment line follows configuration JSON.
    const lines = source.split("\n");
    const firstBodyIndex = lines.findIndex((line) => !line.startsWith("//"));
    expect(lines.slice(firstBodyIndex).some((line) => line.startsWith("//"))).toBe(false);
    expect(firstBodyIndex).toBe(commentLines.length);

    // Every comment line is valid JSONC, and the remaining document is the unchanged configuration.
    expect(parseGeneratedJsonc(source)).toEqual({
      $schema: "https://opencode.ai/config.json",
      instructions: [".agent-profile-kit/opencode/context.md"],
    });
    expect(config.remedyKey).toBe(OPENCODE_CONFIG_OCCUPIED_REMEDY_KEY);
    expect(config.requirements).toEqual([
      "OpenCode loads Profile Context through owned configuration instruction reference",
    ]);
  });

  test("emits no Host configuration when the Profile needs none", async () => {
    const plan = await planOpenCodeProject("engineering", [], []);
    expect(plan.outputs.some((output) => output.path === OPENCODE_CONFIG_PATH)).toBe(false);
  });
});
