/**
 * Generated-source notice policy for material projected out of the Workspace
 * (spec #491, US-021, DEC-014; ticket #503).
 *
 * One concise notice states that projected output is generated, that lasting
 * edits belong to the canonical Workspace source, and that replacing or
 * removing independently changed generated files needs explicit consent. Each
 * Adapter renders this policy in the comment syntax its output format accepts;
 * the notice explains the projection only. It grants no ownership, merges no
 * user configuration, and adds no projection requirement.
 */

/** Canonical notice prefix naming the generator. */
export const GENERATED_SOURCE_NOTICE = "Generated by apkit.";

/** Canonical guidance directing lasting edits to the canonical Workspace source. */
export const GENERATED_SOURCE_WORKSPACE_GUIDANCE =
  "Make lasting edits in the Workspace (apkit open).";

/**
 * Canonical changed-file protection statement; never claims automatic
 * replacement. It names the lifecycle commands that own changed-file consent,
 * because a Temporary Profile Installation is removed by its own explicit
 * teardown command rather than through that consent gate.
 */
export const GENERATED_SOURCE_CONSENT_GUIDANCE =
  "Replacing or removing independently changed files requires explicit consent in install, update, and uninstall.";

/** One notice whose source-location guidance suits the generated format. */
export function generatedSourceGuidance(sourceGuidance: string): string {
  return `${GENERATED_SOURCE_NOTICE} ${sourceGuidance} ${GENERATED_SOURCE_CONSENT_GUIDANCE}`;
}

/** The notice as one format-valid Markdown comment line. */
export function generatedMarkdownNotice(
  sourceGuidance: string = GENERATED_SOURCE_WORKSPACE_GUIDANCE,
): string {
  return `<!-- ${generatedSourceGuidance(sourceGuidance)} -->`;
}

/**
 * Compose one Skill entry document with the notice as the first body line.
 * Frontmatter stays first so Skill metadata and Host consumption are unchanged,
 * and the notice never becomes frontmatter or Skill policy.
 */
export function composeSkillEntryDocument(frontmatter: string, body: string): string {
  return `${frontmatter}${generatedMarkdownNotice()}\n${body}`;
}
